### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Gallagator** [frewsxcv/rust-threadpool#110]
Hi, I think this crate has a memory leak. When building then running with valgrind: I get the following output:
![Screenshot_20210424_223012](https://user-images.githubusercontent.com/37050440/115973413-a2a8c880-a54c-11eb-84d3-dc06fad471e2.png)
If I make the loop run longer, more memory leaks: 
![image](https://user-images.githubusercontent.com/37050440/115973427-cb30c280-a54c-11eb-96fe-f01959af5a9a.png)
Hopefully this can be fixed.

**Comment by dns2utf8** [comment]
Hi @Gallagator 

Thank you for finding this. I will try to reproduce it tonight.

Cheers,
Stefan

**Comment by dns2utf8** [comment]
Hi @Gallagator 

I found the source of the memory leak: 
the worker threads are still in their cleanup phase when valgrind takes the measurement.
Rusts thread model then kills the worker threads at the end of `fn main`, leaking the memory.

For pools of version `1.x` you have to wait a bit after the pool gets dropped:
```rust
use threadpool::ThreadPool;

fn main() {
    for _ in 0..1024 {
        let pool = ThreadPool::new(100);
    }
    std::thread::sleep(std::time::Duration::from_secs(1));
    println!("Bye, world!");
}
```
valgrind run:
```bash
$ cargo build --release && valgrind --leak-check=full target/release/rust_threadpool_memoryleak
==353777== Memcheck, a memory error detector
==353777== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==353777== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==353777== Command: target/release/rust_threadpool_memoryleak
==353777== 
Bye, world!
==353777== 
==353777== HEAP SUMMARY:
==353777==     in use at exit: 0 bytes in 0 blocks
==353777==   total heap usage: 81,422 allocs, 81,422 frees, 4,306,400 bytes allocated
==353777== 
==353777== All heap blocks were freed -- no leaks are possible
==353777== 
==353777== For lists of detected and suppressed errors, rerun with: -s
==353777== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

I will consider this problem in the design of `2.x`, but for now there is not much one can do.
If you have any further questions, feel free to ask again.

Hope this helps.
Cheers,
Stefan
