### ISSUE TITLE
Question on panicking threads 

### ISSUE THREAD

**Issue by ionut-arm** [frewsxcv/rust-threadpool#112]
Hi!

I had a question around what happens when a job panics - is that thread essentially "dead" for the rest of the runtime of the pool? Apologies if this is documented or implied somewhere.

**Comment by oldaccountdeadname** [comment]
> I had a question around what happens when a job panics - is that
> thread essentially "dead" for the rest of the runtime of the pool?

I haven't taken a look at the implementation, but it shouldn't. See
https://docs.rs/threadpool:

> Spawns a specified number of worker therads and replinishes the pool
> if any worker therads panic.

**Comment by dns2utf8** [comment]
The pool has a panic handler that:
1. lets the worker cleanly shutdown
2. spawns a new worker to continue working on the queue

You can check the number of threads that paniced with
[ThreadPool::panic_count(&self)](https://docs.rs/threadpool/latest/threadpool/struct.ThreadPool.html#method.panic_count)

I am closing this issue for now, feel free to reopen it if you have further questions

**Comment by ionut-arm** [comment]
🤦🏻  Thanks for the explanations and details! Don't know how I missed that in the public docs.
