### ISSUE TITLE
Use Formatter utilities to format debug display

### ISSUE THREAD

**Issue by frewsxcv** [frewsxcv/rust-threadpool#53]
https://github.com/frewsxcv/rust-threadpool/blob/322f8f9fc6a16e5a66ecb5fabe4cf784214f835c/lib.rs#L322-L330

When I first wrote this, I wasn't aware of the utilities like [`Formatter::debug_struct`](https://doc.rust-lang.org/nightly/std/fmt/struct.Formatter.html#method.debug_struct). This `Debug` implementation should be rewritten to use these utilities.

**Comment by opilar** [comment]
@frewsxcv this issue can be closed now.
