### ISSUE TITLE
Clarify documentation about deadlocking

### ISSUE THREAD

**Issue by robinst** [frewsxcv/rust-threadpool#56]
The way this sentence is currently phrased, it sounds like it will deadlock as soon as you submit a job when no worker is available:

> Keep in mind, if you put more jobs in the pool than you have workers, you will end up with a deadlock

But that doesn't seem to be the case, this works nicely:

```rust
extern crate threadpool;

use threadpool::ThreadPool;
use std::time::Duration;
use std::thread::sleep;

fn main() {
    let pool = ThreadPool::new(2);
    for _ in 0..5 {
        pool.execute(move || {
            println!("Executing job");
            sleep(Duration::from_secs(1));
        });
        println!("Submitted job");
    }
    sleep(Duration::from_secs(5));
    println!("Active: {}", pool.active_count());
}

```

Will print:

> Submitted job
> Executing job
> Submitted job
> Submitted job
> Submitted job
> Submitted job
> Executing job
> Executing job
> Executing job
> Executing job
> Active: 0

Can you clarify what is meant in that section? As far as I can tell, the danger is when you block in the job execution on something that is outside of it and that depends on the job execution as well.

**Comment by dns2utf8** [comment]
The wording is not referencing it directly but this applies only to code with locks or barriers under which the section is.
The problem is that you will produce a deadlock as soon as you try to synchronize more jobs than you have threads:

```rust
extern crate threadpool;

use threadpool::ThreadPool;
use std::time::Duration;
use std::thread::sleep;
use std::sync::{Arc, Barrier};

fn main() {
    let n_threads = 5;
    let n_jobs = n_threads + 1;

    let pool = ThreadPool::new(n_threads);
    // Syncs the pool, +1 if you would like to sync the whole application
    let barrier = Arc::new(Barrier::new(n_jobs /* +1 */));

    for i in 0..n_jobs {
        let barrier = barrier.clone();
        pool.execute(move || {
            println!("Executing job {}", i);

            barrier.wait();

            println!("Finished job {}", i);
        });
        println!("Submitted job {}", i);
    }

    // barrier.wait(); // Without this barrier, the main thread will kill the pool
    sleep(Duration::from_secs(6));
    println!("Active: {}", pool.active_count());
}
```

**Comment by robinst** [comment]
Much better with the merged PR.
