### ISSUE TITLE
Spurious failure with 'test_massive_task_creation' test

### ISSUE THREAD

**Issue by frewsxcv** [frewsxcv/rust-threadpool#66]
https://github.com/frewsxcv/rust-threadpool/blob/f8b13ee8a00386e63d9d430a5f9612bb51fd8b93/lib.rs#L553

example of failure: https://travis-ci.org/frewsxcv/rust-threadpool/jobs/251542770 via https://github.com/frewsxcv/rust-threadpool/pull/64
```
---- test::test_massive_task_creation stdout ----

	thread 'test::test_massive_task_creation' panicked at 'atomic_active_count: 2', lib.rs:553:8
```

**Comment by bblancha** [comment]
When #63 gets merged, we should be able use use it to eliminate the race.

https://github.com/bblancha/rust-threadpool/blob/massive_task_creation_fix/lib.rs#L599

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/rust-threadpool/pull/63 has merged
